// App Store category IDs (genre IDs)
export const CATEGORIES: Record<string, number> = {
  // Main categories
  "books": 6018,
  "business": 6000,
  "developer-tools": 6026,
  "education": 6017,
  "entertainment": 6016,
  "finance": 6015,
  "food-drink": 6023,
  "games": 6014,
  "graphics-design": 6027,
  "health-fitness": 6013,
  "lifestyle": 6012,
  "magazines-newspapers": 6021,
  "medical": 6020,
  "music": 6011,
  "navigation": 6010,
  "news": 6009,
  "photo-video": 6008,
  "productivity": 6007,
  "reference": 6006,
  "shopping": 6024,
  "social-networking": 6005,
  "sports": 6004,
  "travel": 6003,
  "utilities": 6002,
  "weather": 6001,

  // Game subcategories
  "action-games": 7001,
  "adventure-games": 7002,
  "arcade-games": 7003,
  "board-games": 7004,
  "card-games": 7005,
  "casino-games": 7006,
  "casual-games": 7003,
  "dice-games": 7007,
  "educational-games": 7008,
  "family-games": 7009,
  "music-games": 7011,
  "puzzle-games": 7012,
  "racing-games": 7013,
  "role-playing-games": 7014,
  "simulation-games": 7015,
  "sports-games": 7016,
  "strategy-games": 7017,
  "trivia-games": 7018,
  "word-games": 7019,
};

// Category display names
export const CATEGORY_NAMES: Record<string, string> = {
  "books": "Books",
  "business": "Business",
  "developer-tools": "Developer Tools",
  "education": "Education",
  "entertainment": "Entertainment",
  "finance": "Finance",
  "food-drink": "Food & Drink",
  "games": "Games",
  "graphics-design": "Graphics & Design",
  "health-fitness": "Health & Fitness",
  "lifestyle": "Lifestyle",
  "magazines-newspapers": "Magazines & Newspapers",
  "medical": "Medical",
  "music": "Music",
  "navigation": "Navigation",
  "news": "News",
  "photo-video": "Photo & Video",
  "productivity": "Productivity",
  "reference": "Reference",
  "shopping": "Shopping",
  "social-networking": "Social Networking",
  "sports": "Sports",
  "travel": "Travel",
  "utilities": "Utilities",
  "weather": "Weather",
  "action-games": "Action Games",
  "adventure-games": "Adventure Games",
  "arcade-games": "Arcade Games",
  "board-games": "Board Games",
  "card-games": "Card Games",
  "casino-games": "Casino Games",
  "casual-games": "Casual Games",
  "dice-games": "Dice Games",
  "educational-games": "Educational Games",
  "family-games": "Family Games",
  "music-games": "Music Games",
  "puzzle-games": "Puzzle Games",
  "racing-games": "Racing Games",
  "role-playing-games": "Role Playing Games",
  "simulation-games": "Simulation Games",
  "sports-games": "Sports Games",
  "strategy-games": "Strategy Games",
  "trivia-games": "Trivia Games",
  "word-games": "Word Games",
};

// Country codes
export const COUNTRY_CODES: Record<string, string> = {
  "us": "United States",
  "gb": "United Kingdom",
  "ca": "Canada",
  "au": "Australia",
  "de": "Germany",
  "fr": "France",
  "jp": "Japan",
  "cn": "China",
  "kr": "South Korea",
  "in": "India",
  "br": "Brazil",
  "mx": "Mexico",
  "es": "Spain",
  "it": "Italy",
  "nl": "Netherlands",
  "se": "Sweden",
  "no": "Norway",
  "dk": "Denmark",
  "fi": "Finland",
  "ru": "Russia",
  "pl": "Poland",
  "tr": "Turkey",
  "sa": "Saudi Arabia",
  "ae": "UAE",
  "sg": "Singapore",
  "hk": "Hong Kong",
  "tw": "Taiwan",
  "nz": "New Zealand",
  "ie": "Ireland",
  "at": "Austria",
  "ch": "Switzerland",
  "be": "Belgium",
  "pt": "Portugal",
};

// Main categories (non-game)
export const MAIN_CATEGORIES = Object.keys(CATEGORIES).filter(
  key => !key.includes('games') || key === 'games'
);

// Game subcategories
export const GAME_SUBCATEGORIES = Object.keys(CATEGORIES).filter(
  key => key.includes('games') && key !== 'games'
);

// Organized category groups for collapsible UI
export const CATEGORY_GROUPS: Record<string, { label: string; icon: string; categories: string[] }> = {
  'entertainment-media': {
    label: 'Entertainment & Media',
    icon: '🎬',
    categories: ['entertainment', 'music', 'photo-video', 'magazines-newspapers', 'news', 'books'],
  },
  'games': {
    label: 'Games',
    icon: '🎮',
    categories: [
      'games',
      'action-games',
      'adventure-games',
      'arcade-games',
      'board-games',
      'card-games',
      'casino-games',
      'casual-games',
      'dice-games',
      'educational-games',
      'family-games',
      'music-games',
      'puzzle-games',
      'racing-games',
      'role-playing-games',
      'simulation-games',
      'sports-games',
      'strategy-games',
      'trivia-games',
      'word-games',
    ],
  },
  'business-productivity': {
    label: 'Business & Productivity',
    icon: '💼',
    categories: ['business', 'productivity', 'finance', 'developer-tools'],
  },
  'health-lifestyle': {
    label: 'Health & Lifestyle',
    icon: '🏃',
    categories: ['health-fitness', 'medical', 'food-drink', 'lifestyle', 'sports'],
  },
  'social-communication': {
    label: 'Social & Communication',
    icon: '💬',
    categories: ['social-networking', 'reference'],
  },
  'education-reference': {
    label: 'Education & Reference',
    icon: '📚',
    categories: ['education', 'reference'],
  },
  'utilities-tools': {
    label: 'Utilities & Tools',
    icon: '🔧',
    categories: ['utilities', 'weather', 'navigation', 'graphics-design'],
  },
  'shopping-travel': {
    label: 'Shopping & Travel',
    icon: '🛒',
    categories: ['shopping', 'travel'],
  },
};
